---
- hosts: host2
  tasks:
  - name: "Update apt cache"
    become: yes
    apt:
      update_cache: yes

  - name: "Install nginx package"
    become: yes
    apt:
      name: "nginx"
      state: present

  - name: "Stop nginx service"
    become: yes
    service:
      name: nginx
      state: stopped

#  - name: "Copy config file"
 
  - name: "Start and Enable nginx service"
    become: yes
    service:
      name: nginx
      state: started
      enabled: yes
