---
- hosts: host2
  tasks:
  - name: Check if NGINX exists
    shell: systemctl --type=service | grep "nginx.service"
    ignore_errors: yes
    register: nginx_service

  - name: Stop nginx service
    become: yes
    service:
      name: nginx
      state: stopped
    when: nginx_service.stdout | length > 0

  - name: Update and install apache2
    become: yes
    apt:
      update_cache: yes
      name: apache2
      state: present

  - name: enable SSL support
    become: yes
    shell: a2enmod ssl

  - name: stop apache2 service
    become: yes
    service:
      name: apache2
      state: stopped

  - name: Remove ports.conf file
    become: yes
    file:
      path: /etc/apache2/ports.conf
      state: absent
 
  - name: Copy modified ports.conf file
    become: yes
    copy:
      src: /home/hikedaya/ansible/apache/config/ports.conf
      dest: /etc/apache2/ports.conf

  - name: start apache2 service
    become: yes
    service:
      name: apache2
      state: started
 
  - name: "Start nginx service if was stopped"
    become: yes
    service:
      name: nginx
      state: started
    when: nginx_service.stdout | length > 0
